### ISSUE TITLE
port speed shows incorrectly for ports under 1G

### ISSUE THREAD

**Issue by grizz** [peeringdb/1to2#16]
For example, https://beta.peeringdb.com/ix/34

**Comment by huggi** [comment]
well, I just looked at the affected ISP, https://beta.peeringdb.com/net/2192 then I see that they only have a 100Mbps port, which is of course 0.1 G and treated as 0G if I'm correct.

**Comment by grizz** [comment]
fixed b813c02

**Comment by huggi** [comment]
Sorry, but the output at: https://beta.peeringdb.com/ix/34 is still the same (assuming you did change something in the running codebase)?!

**Comment by grizz** [comment]
It's not deployed yet, no. The next release will also have a nice little version tag in the bottom left corner :)

**Comment by huggi** [comment]
Okay, did not know that, then let it closed :)

On 15 April 2015 at 13:40, Matt Griswold <notifications@github.com> wrote:

> It's not deployed yet, no. The next release will also have a nice little
> version tag in the bottom left corner :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/peeringdb/1to2/issues/16#issuecomment-93202719>.
>



-- 
Cheers

Marco Huggenberger
http://about.me/huggi
